export const FundList = [
  {
    title: "광주은행",
    price: "최대 5.20%",
    icon: "https://i.imgur.com/1SjkQIc.png",
    link: "",
    month_1: "4.00%",
    month_2: "4.50%",
    month_3: "5.20%",
  },
  {
    title: "NH농협은행",
    price: "최대 5.00%",
    icon: "https://i.imgur.com/lDGHW0N.png",
    link: "",
    month_1: "3.00%",
    month_2: "4.00%",
    month_3: "5.00%",
  },
  {
    title: "신한은행",
    icon: "https://i.imgur.com/llOPDaz.png",
    price: "최대 5.00%",
    link: "",
    month_1: "4.00%",
    month_2: "4.50%",
    month_3: "5.00%",
  },
  {
    title: "우리은행",
    icon: "https://i.imgur.com/RO9qPPo.png",
    price: "최대 5.00%",
    link: "",
    month_1: "3.50%",
    month_2: "4.00%",
    month_3: "5.00%",
  },
  {
    title: "하나은행",
    price: "최대 5.00%",
    icon: "https://i.imgur.com/0TwOFgZ.png",
    link: "",
    month_1: "3.50%",
    month_2: "4.00%",
    month_3: "5.00%",
  },
  {
    title: "IBK기업은행",
    price: "최대 5.00%",
    icon: "https://i.imgur.com/TozvbDZ.png",
    link: "",
    month_1: "4.00%",
    month_2: "4.50%",
    month_3: "5.00%",
  },
  {
    title: "KB국민은행",
    price: "최대 5.00%",
    icon: "https://i.imgur.com/yQOac30.png",
    link: "",
    month_1: "3.50%",
    month_2: "4.50%",
    month_3: "5.00%",
  },
  {
    title: "DGB대구은행",
    price: "최대 5.00%",
    icon: "https://i.imgur.com/FEJtLn5.png",
    link: "",
    month_1: "4.00%",
    month_2: "4.05%",
    month_3: "5.00%",
  },
  {
    title: "제주은행",
    price: "최대 5.00%",
    icon: "https://i.imgur.com/HJNRfIl.png",
    link: "",
    month_1: "4.00%",
    month_2: "4.50%",
    month_3: "5.00%",
  },
  {
    title: "전북은행",
    price: "최대 5.00%",
    icon: "https://i.imgur.com/cTUwzxD.png",
    link: "",
    month_1: "3.60%",
    month_2: "4.10%",
    month_3: "5.00%",
  },
  {
    title: "우체국",
    price: "최대 5.00%",
    icon: "https://i.imgur.com/STfCLaX.png",
    link: "",
    month_1: "4.00%",
    month_2: "4.50%",
    month_3: "5.00%",
  },
  {
    title: "SH수협은행",
    price: "최대 4.50%",
    icon: "https://i.imgur.com/ZpsTCza.png",
    link: "",
    month_1: "2.50%",
    month_2: "3.50%",
    month_3: "4.50%",
  },
  {
    title: "BNK부산은행",
    price: "최대 4.50%",
    icon: "https://i.imgur.com/RX1V26T.png",
    link: "",
    month_1: "3.50%",
    month_2: "4.00%",
    month_3: "4.50%",
  },
  {
    title: "BNK경남은행",
    price: "최대 4.50%",
    icon: "https://i.imgur.com/0ZAme5b.png",
    link: "",
    month_1: "3.10%",
    month_2: "3.90%",
    month_3: "4.50%",
  },
];
